language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - sudo apt-get install graphviz
  - "python setup.py install"
  - "pip install nose==1.3.7"
  - "pip install coverage==3.6"
  - "pip install coveralls"

script:
  - nosetests --cover-package=anytree

after_success:
  coveralls
